---
ID: "d054dc2b-fa55-4afe-9f54-079b79c260f6"
Parent: "ffe6d999-ad2a-4204-ade8-f42104d92cd3"
Template: "ffe6d999-ad2a-4204-ade8-f42104d92cd3"
Path: /sitecore/templates/Project/teamhorizon2024/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T093331Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\julius.angwenyi@accenture.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\julius.angwenyi@accenture.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "141a432f-04f2-4de4-99f7-36cc2d1e5654"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\julius.angwenyi@accenture.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T093331Z
